workflows:
  unit-tests:
    environment:
      xcode: 13.0
    cache:
      cache_paths:
        - "~/Library/Caches/org.swift.swiftpm/"
    scripts:
      - name: Build and test
        script: |
          xcodebuild build-for-testing test-without-building \
          -workspace composable-much-better-exercise.xcworkspace \
          -scheme "AllTests" \
          -destination "platform=iOS Simulator,OS=15.0,name=iPhone 13" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
  spend-unit-tests:
    environment:
      xcode: 13.0
    scripts:
      - name: Build
        script: |
          xcodebuild build-for-testing \
          -workspace composable-much-better-exercise.xcworkspace \
          -scheme "SpendTests" \
          -destination "platform=iOS Simulator,OS=15.0,name=iPhone 13" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      - name: Spend module
        script: |
          xcodebuild test-without-building \
          -workspace composable-much-better-exercise.xcworkspace \
          -scheme "SpendTests" \
          -destination "platform=iOS Simulator,OS=15.0,name=iPhone 13" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
  transaction-unit-tests:
    environment:
      xcode: 13.0
    scripts:
      - name: Transaction module
        script: |
          xcodebuild test-without-building \
          -workspace composable-much-better-exercise.xcworkspace \
          -scheme "TransactionTests" \
          -destination "platform=iOS Simulator,OS=15.0,name=iPhone 13" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        test_report: build/ios/test/*.xml
  balance-unit-tests:
    environment:
      xcode: 13.0
    scripts:
      - name: Balance module
        script: |
          xcodebuild test-without-building \
          -workspace composable-much-better-exercise.xcworkspace \
          -scheme "BalanceTests" \
          -destination "platform=iOS Simulator,OS=15.0,name=iPhone 13" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        test_report: build/ios/test/*.xml
  login-unit-tests:
    environment:
      xcode: 13.0
    scripts:
      - name: Login module
        script: |
          xcodebuild test-without-building \
          -workspace composable-much-better-exercise.xcworkspace \
          -scheme "LoginTests" \
          -destination "platform=iOS Simulator,OS=15.0,name=iPhone 13" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        test_report: build/ios/test/*.xml